spring:
  application:
    name: biblioteca

  data:
    mongodb:
      uri: mongodb://localhost:27017/biblioteca
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutos em milissegundos (TTL padrão)

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.sicredi.biblioteca: DEBUG
    org.springframework.cache: DEBUG